apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: django-deployment 
spec: 
  selector: 
    matchLabels: 
      app: django 
  replicas: 2 
  template: 
    metadata: 
      labels: 
        app: django 
    spec: 
      containers: 
      - name: django
        image: hamzaabdouli/medicashare_vf_django:v1
        ports: 
        - containerPort: 80

---

kind: Service 
apiVersion: v1 
metadata: 
  name: django-service 
spec: 
  selector: 
    app: django 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 31000 
  type: NodePort 