version: "3.8"
   
services:
    django:
        image: hamzaabdouli/medicashare_vf_django:v1
        #build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/django-app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: hamzaabdouli/postgres:v1
        container_name: pgdb
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
