---
- hosts: all
  tasks:
  - name: Run container
    become: True
    shell:
      cmd: "docker-compose up"
      chdir: /home/hamza/Desktop/medicashare_vf/

  - name: Deploy django&service to kubernetes
    command: kubectl apply -f deployment_django.yaml

  - name: Deploy postgres&service to kubernetes
    command: kubectl apply -f deployment_postgres.yml