---
- hosts: all
  tasks:
  - name: Run container
    become: True
    shell:
      cmd: "docker-compose up"
      chdir: /home/hamza/Desktop/medicashare_vf/

  - name: Run container
    command: kubectl apply -f deployment_local.yaml
