---
- hosts: all
  tasks:
  - name: Kubernetes Create Postgres PersistentVolume
    become: False
    shell:
      cmd: "kubectl apply -f volume.yml"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project2/deploy/kubernetes/postgres/
      

  - name: Kubernetes Create Postgres PersistentVolumeClaim
    become: False
    shell:
      cmd: "kubectl apply -f volume_claim.yml"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project2/deploy/kubernetes/postgres/

  - name: Kubernetes Create Postgres Secret
    become: False
    shell:
      cmd: "kubectl apply -f secrets.yml"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project2/deploy/kubernetes/postgres/

  - name: Kubernetes Create Postgres Service
    become: False
    shell:
      cmd: "kubectl apply -f service.yml"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project2/deploy/kubernetes/postgres/

  - name: Kubernetes Create Postgres Deployment
    become: False
    shell:
      cmd: "kubectl apply -f deployment.yml"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project2/deploy/kubernetes/postgres/   

  - name: Kubernetes Create Django yml files 
    become: False
    shell:
      cmd: "kubectl apply -f django/"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project2/deploy/kubernetes/ 

  - name: Kubernetes Create namespace
    command : kubectl create ns monitoring    

  - name: Kubernetes Create Prometheus yml files 
    become: False
    shell:
      cmd: "kubectl apply -f prometheus/"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project2/deploy/kubernetes/    

  - name: Kubernetes Create Grafana yml files 
    become: False
    shell:
      cmd: "kubectl apply -f grafana/"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project2/deploy/kubernetes/        




