---
- hosts: all
  tasks:
  - name: Kubernetes Create Postgres PersistentVolume
    become: True
    shell:
      cmd: "kubectl apply -f volume.yml"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project/kubernetes/postgres/

  - name: Kubernetes Create Postgres PersistentVolumeClaim
    become: True
    shell:
      cmd: "kubectl apply -f volume_claim.yml"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project/kubernetes/postgres/

  - name: Kubernetes Create Postgres Service
    become: True
    shell:
      cmd: "kubectl apply -f service.yml"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project/kubernetes/postgres/

  - name: Kubernetes Create Postgres Deployment
    become: True
    shell:
      cmd: "kubectl apply -f deployment.yml"
      chdir: /home/hamza/.jenkins/workspace/DevOps_Project/kubernetes/postgres/     
