# Generated by Django 3.0.7 on 2020-06-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200415_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='a.jpg', upload_to='medicament_images'),
        ),
    ]
