# Generated by Django 3.0.7 on 2020-06-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('R', 'Request'), ('D', 'Donation')], max_length=100, null=True),
        ),
    ]
