# Generated by Django 3.0.7 on 2020-07-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_post_expirattion_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('expirattion_date',)},
        ),
        migrations.AddField(
            model_name='post',
            name='isGived',
            field=models.CharField(default='no', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='expirattion_date',
            field=models.DateField(),
        ),
    ]
