# Generated by Django 3.0.7 on 2020-07-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200703_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isGived',
            field=models.CharField(default='no', max_length=6),
        ),
    ]
