# Generated by Django 3.0.7 on 2020-07-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200703_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expirattion_date',
            field=models.DateField(auto_now=True),
        ),
    ]
