# Generated by Django 3.0.7 on 2020-07-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200703_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isGived',
            new_name='isDonated',
        ),
        migrations.AddField(
            model_name='post',
            name='isReceived',
            field=models.CharField(default='no', max_length=6),
        ),
    ]
